Feature/contract caller
DogukanGun/NearBridge pull request #7
Opened 2023-10-11 14:32 UTC by cemdenizsel

**What is done:**

- [x ] Feature added
- [x ] Bug fixed
- [ ] Code refactored
- [ ] Documentation updated
- [ ] Tests added
- [ ] Other (please specify):

### PR Purpose

Contract calling functionality added.

2023-10-11 14:37 UTC, DogukanGun requested changes

2023-10-11 14:37 UTC, DogukanGun commented on bridge/nearclient/contract_caller.go
> +func main() {
Instead of putting this code here, could you open a new file as near....Example and place this function there

2023-10-11 18:45 UTC, cemdenizsel commented on bridge/nearclient/contract_caller.go
> +func main() {
done!

2023-10-13 14:43 UTC, DogukanGun approved these changes

2023-10-13 14:43 UTC, merged